services:
  - type: web
    name: kelvin-chwara-portfolio
    env: static
    buildCommand: npm run build
    publishPath: build
    routes:
      - route: /*
        redirect:
          statusCode: 200
          destination: /index.html